FROM golang:1.7-alpine

RUN apk update && apk add git

CMD ["go", "get", "-d", "github.com/qeas/nedge-docker-nfs/..."]

WORKDIR $GOPATH/src/github.com/qeas/nedge-docker-nfs

CMD ["git", "checkout", "v2_plugin"]

CMD ["go", "get", "github.com/qeas/nedge-docker-nfs/..."]
