FROM golang:1.7-alpine

RUN apk update && apk add git

RUN go get -d github.com/qeas/nedge-docker-nfs/... && cd $GOPATH/src/github.com/qeas/nedge-docker-nfs && git checkout v2_plugin && go get github.com/qeas/nedge-docker-nfs/...
