FROM golang:1.7-alpine

RUN apk update && apk add git

CMD ["go", "get", "-d", "github.com/qeas/nedge-docker-nfs/..."]

RUN cd $GOPATH/src/github.com/qeas/nedge-docker-nfs && git checkout v2_plugin

CMD ["go", "get", "github.com/qeas/nedge-docker-nfs/..."]
